# Generated by Django 4.0.3 on 2022-10-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_automobilevo_import_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='is_vip',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='model',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='year',
        ),
    ]
